<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Biz.Bizadm.KMS.Credentials</RootNamespace>
		<AssemblyName>Biz.Bizadm.KMS.Credentials.Runtime</AssemblyName>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Version>1.0.0</Version>
		<Authors>SeongSikChae</Authors>
		<Description>Internal implementation package not meant for direct consumption. Please do not reference directly. Windows Credential Manager IKekCredentialProvider for Biz.Bizadm.KMS.Credentials.</Description>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<Compile Include="..\Biz.Bizadm.KMS.Credentials.Shared\**\*.cs" Link="Shared\%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Biz.Bizadm.KMS.Credentials\Biz.Bizadm.KMS.Credentials.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Devlooped.CredentialManager" Version="2.7.0" />
	</ItemGroup>

</Project>
