<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Biz.Bizadm.KMS\Biz.Bizadm.KMS.csproj" />
    <ProjectReference Include="..\Biz.Bizadm.KMS.Protect\Biz.Bizadm.KMS.Protect.csproj" />
    <ProjectReference Include="..\runtime.win.Biz.Bizadm.KMS.Protect\runtime.win.Biz.Bizadm.KMS.Protect.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
