<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Biz.Bizadm.KMS\Biz.Bizadm.KMS.csproj" />
    <ProjectReference Include="..\Biz.Bizadm.KMS.Credentials\Biz.Bizadm.KMS.Credentials.csproj" />
    <ProjectReference Include="..\Biz.Bizadm.KMS.Credentials.Runtime.linux\Biz.Bizadm.KMS.Credentials.Runtime.linux.csproj" />
  </ItemGroup>

</Project>

